apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
           echo "=== string before masking ==="
           echo "hello world"
           echo -n "hello" | cloudbees mask
           echo "=== string after masking ==="
           echo "hello world"
