apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  maskvalue:
    steps:
      - name: mask
        uses: docker://alpine:3.18
        run: |
           echo "=== string before masking ==="
           echo "hello world"
           echo -n "hello" | cloudbees mask
           echo "=== string after masking ==="
           echo "hello world"
